"""
Case Review page.

Shows a single flagged record with SHAP explanation, Gemini plain English
explanation, analyst chat, and decision actions.

TODO: update display fields, actions, and Gemini calls for {{PROJECT_NAME}}.

Owner(s):
"""

import streamlit as st
import pandas as pd
from app.components.score_badge import score_badge
from app.components.shap_chart import shap_waterfall


def render():
    st.title("Case Review")

    if st.session_state.get("current_record") is None:
        st.info("Select a record from the Review Queue to open it here.")
        return

    rec = st.session_state.current_record

    col1, col2, col3 = st.columns([2, 1, 1])
    with col1:
        # TODO: update ID field for {{PROJECT_NAME}}
        st.markdown(f"**Record ID:** `{rec.get('id', 'N/A')}`")
    with col2:
        st.metric("Prediction score", f"{rec.get('pred_prob', 0):.1%}")
    with col3:
        score_badge(rec.get("score_tier", "Low"))

    st.divider()

    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("Record details")
        # TODO: replace with actual fields for {{PROJECT_NAME}}
        st.json({k: v for k, v in rec.items() if k not in ["pred_prob", "pred_flag", "risk_tier"]})

    with col_right:
        st.subheader("Why this was flagged")
        if st.session_state.get("current_shap_df") is not None:
            shap_waterfall(st.session_state.current_shap_df)
        else:
            st.caption("SHAP data not available for this record.")

    st.divider()

    st.subheader("{{PERSONA}} explanation")
    st.caption("Generated by Gemini AI. Advisory only. The prediction score above is the authoritative decision.")

    if st.button("Generate explanation", key="gen_explain"):
        try:
            from src.gemini import explain_prediction
            shap_df = st.session_state.get("current_shap_df", pd.DataFrame())
            with st.spinner("Generating explanation..."):
                explanation = explain_prediction(record=rec, shap_df=shap_df, stream=False)
            st.session_state.gemini_explanation = explanation
        except Exception as e:
            st.error(f"Gemini explanation failed: {e}")

    if st.session_state.get("gemini_explanation"):
        st.info(st.session_state.gemini_explanation)

    st.divider()

    st.subheader("Ask a question about this record")
    st.caption("Powered by Gemini AI.")

    for msg in st.session_state.get("chat_history", []):
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    user_input = st.chat_input("Ask anything about this record...")
    if user_input:
        st.session_state.chat_history.append({"role": "user", "content": user_input})
        try:
            from src.gemini import chat_with_user
            history = [
                {"role": m["role"], "parts": [m["content"]]}
                for m in st.session_state.chat_history[:-1]
            ]
            reply = chat_with_user(
                user_message=user_input,
                conversation_history=history,
                record_context=rec,
                related_history=st.session_state.get("related_history", []),
            )
        except Exception as e:
            reply = f"Unable to answer: {e}"
        st.session_state.chat_history.append({"role": "assistant", "content": reply})
        st.rerun()

    st.divider()

    st.subheader("Decision")
    c1, c2, c3 = st.columns(3)
    rec_id = rec.get("id", "unknown")

    # TODO: update action labels for {{PROJECT_NAME}} and {{PERSONA}}
    with c1:
        if st.button("Approve", type="secondary", use_container_width=True):
            st.session_state.user_actions[rec_id] = "approved"
            st.success("Record approved.")
    with c2:
        if st.button("Flag for review", type="primary", use_container_width=True):
            st.session_state.user_actions[rec_id] = "flagged"
            st.warning("Record flagged.")
    with c3:
        if st.button("Escalate", type="primary", use_container_width=True):
            st.session_state.user_actions[rec_id] = "escalated"
            st.error("Record escalated.")
